### ISSUE TITLE
CC removal, regex improvements

### ISSUE THREAD

**Issue by phaax** [bernhardc/netflix-tweaks#1]
There's a few issues with the CC removal that I've noticed. Sometimes there will be a single `-<br>` or `<br>-` left visible after it has removed the CC portion.

I'm not an expert with regular expressions in any way shape or form. But I modified the removeCCSubs to catch those cases that the original regex missed. This hasn't been tested very much, but it seems to work well so far. 

```
if (options['removeCCSubs']) {
	after = before
		.replace(/-?\s?\[.*\]\s*/g, "")
		.trim()
		.replace(/^-?\s*<br>\s*-?\s*$/g, "")
		.trim()
}
```

**Comment by bernie43** [comment]
Thanks for reporting! I added your suggestion, although with a bit different syntax to keep things simple.
